(function(){var f=true,g=null,j=false,k=this,aa=function(a,b,c){a=a.split(".");c=c||k;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)if(!a.length&&b!==undefined)c[d]=b;else c=c[d]?c[d]:c[d]={}},ba=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";
if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};Math.floor(Math.random()*2147483648).toString(36);
var m=function(a,b){var c=b||k;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}},o=function(a,b,c){aa(a,b,c)},da=function(a,b,c){a[b]=c},p=function(a,b){function c(){}c.prototype=b.prototype;a.Ba=b.prototype;a.prototype=new c};var q=function(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c},ea=function(a,b){if(a=="true")return f;if(a=="false")return j;return b},fa=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,r=function(a,b){if(!a)return b;var c=a.match(fa);return c?c[0]:b};var ga=function(){return r("","pagead2.googlesyndication.com")};var ja=function(a){if(a.indexOf("&")!=-1)return"document"in k&&a.indexOf("<")==-1?ha(a):ia(a);return a},ha=function(a){var b=k.document.createElement("a");b.innerHTML=a;b.normalize&&b.normalize();a=b.firstChild.nodeValue;b.innerHTML="";return a},ia=function(a){return a.replace(/&([^;]+);/g,function(b,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return b}})},
la=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(d.length,e.length),i=0;c==0&&i<h;i++){var l=d[i]||"",n=e[i]||"",G=RegExp("(\\d*)(\\D*)","g"),z=RegExp("(\\d*)(\\D*)","g");do{var A=G.exec(l)||["","",""],B=z.exec(n)||["","",""];if(A[0].length==0&&B[0].length==0)break;c=A[1].length==0?0:parseInt(A[1],10);var ca=B[1].length==0?0:parseInt(B[1],10);c=ka(c,ca)||ka(A[2].length==0,B[2].length==0)||
ka(A[2],B[2])}while(c==0)}return c},ka=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var s=function(a,b){this.width=a;this.height=b};s.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};s.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var t,ma,na,oa,pa,qa,ra,sa,ta,ua=function(){return k.navigator?k.navigator.userAgent:g},va=function(){return k.navigator},wa=function(){pa=oa=na=ma=t=j;var a;if(a=ua()){var b=va();t=a.indexOf("Opera")==0;ma=!t&&a.indexOf("MSIE")!=-1;oa=(na=!t&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;pa=!t&&!na&&b.product=="Gecko"}};wa();
var xa=t,ya=ma,za=pa,Aa=na,Ba=oa,Ca=function(){var a=va();return a&&a.platform||""},Da=Ca(),Ea=function(){qa=Da.indexOf("Mac")!=-1;ra=Da.indexOf("Win")!=-1;sa=Da.indexOf("Linux")!=-1;ta=!!va()&&(va().appVersion||"").indexOf("X11")!=-1};Ea();var Fa=function(){var a="",b;if(xa&&k.opera){a=k.opera.version;a=typeof a=="function"?a():a}else{if(za)b=/rv\:([^\);]+)(\)|;)/;else if(ya)b=/MSIE\s+([^\);]+)(\)|;)/;else if(Aa)b=/WebKit\/(\S+)/;if(b)a=(a=b.exec(ua()))?a[1]:""}return a},Ga=Fa(),Ha={};var Ia=function(a){var b=a.document;if(Aa&&!(Ha["500"]||(Ha["500"]=la(Ga,"500")>=0))&&!Ba){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new s(a.innerWidth,b)}a=b.compatMode=="CSS1Compat";if(xa&&!(Ha["9.50"]||(Ha["9.50"]=la(Ga,"9.50")>=0)))a=j;a=a?b.documentElement:b.body;return new s(a.clientWidth,a.clientHeight)};var Ja=document,u=window,Ka=function(a){var b=g;if((a=a.getElementsByTagName("script"))&&a.length){b=a[a.length-1];b=b.parentNode}return b};Ka(Ja);var La=!!window.google_async_iframe_id,Ma=La&&window.parent||window;var Na="http://"+ga()+"/pagead/show_ads.js";function v(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function Oa(a,b,c){var d=document.createElement("script");d.type="text/javascript";if(b)d.onload=b;if(c)d.id=c;d.src=a;var e=document.getElementsByTagName("head")[0];if(!e)return j;window.setTimeout(function(){e.appendChild(d)},0);return f}
function Pa(a,b){if(a.attachEvent){a.attachEvent("onload",b);return f}if(a.addEventListener){a.addEventListener("load",b,j);return f}return j}var Qa=function(a){if(!("google_onload_fired"in a)){a.google_onload_fired=j;Pa(a,function(){a.google_onload_fired=f})}};function Ra(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}function w(a){if(a in Sa)return Sa[a];return Sa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var Sa={};
function Ta(){return w("msie")&&!window.opera}
function Ua(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){a=3;for(var b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1));a++}catch(c){b=g}return a.toString()}else if(Ta()){b=g;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
a=6;b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(h){}}if(b){a=b.GetVariable("$version").split(" ")[1];return a.replace(/,/g,".")}}return"0"}function Va(a,b){if(!(Math.random()<1.0E-4)){var c=Math.random();if(c<b){c=Math.floor(c/b*a.length);return a[c]}}return""}
var Wa=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen){a.u_h=window.screen.height;a.u_w=window.screen.width;a.u_ah=window.screen.availHeight;a.u_aw=window.screen.availWidth;a.u_cd=window.screen.colorDepth}if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},Xa=function(a,b){var c=b||u;if(a&&c.top!=c)c=c.top;try{return c.document&&!c.document.body?new s(-1,
-1):Ia(c||window)}catch(d){return new s(-12245933,-12245933)}},Ya=function(a,b){var c=a.length;if(c==0)return 0;for(var d=b||305419896,e=0;e<c;e++){var h=a.charCodeAt(e);d^=(d<<5)+(d>>2)+h&4294967295}return d>0?d:4294967296+d},Za=function(a){if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=f;a=Xa(!c,a);b.push(a.width.toString());b.push(a.height.toString());return Ya(b.join(""))},$a=function(a){if(!a)return"";var b=[],c=0;for(a=a;a&&c<25;a=a.parentNode,++c)b.push(a.id||
"");return b.join()};var ab=q("0.005",0),bb=q("0.01",0),cb=q("0.001",0),db=q("0.006",0),eb=q("0.008",0);var fb=ea("false",j),gb=ea("false",j),hb=ea("false",j),ib=ea("false",j);var jb=function(a,b,c){b=m(b,k,a);a=window.onerror;window.onerror=b;try{c()}catch(d){c=d.toString();var e="";if(d.fileName)e=d.fileName;var h=-1;if(d.lineNumber)h=d.lineNumber;b=b(c,e,h);if(!b)throw d;}window.onerror=a};o("google_protectAndRun",jb);
var lb=function(a,b,c,d){if(Math.random()<0.01){var e=Ja;a=["http://",r("","pagead2.googlesyndication.com"),"/pagead/gen_204","?id=jserror","&jscb=",fb?1:0,"&jscd=",gb?1:0,"&context=",v(a),"&msg=",v(b),"&file=",v(c),"&line=",v(d.toString()),"&url=",v(e.URL.substring(0,512)),"&ref=",v(e.referrer.substring(0,512))];a.push(kb());Ra(u,a.join(""))}return!hb};o("google_handleError",lb);
var kb=function(){var a=["&client=",v(u.google_ad_client),"&format=",v(u.google_ad_format),"&slotname=",v(u.google_ad_slot),"&output=",v(u.google_ad_output),"&ad_type=",v(u.google_ad_type)];return a.join("")};var x=function(){this.Z=[];this.qa=window;this.v=0},mb=function(a,b){this.fn=a;this.win=b};x.prototype.enqueue=function(a,b){this.Z.push(new mb(a,b||this.qa));nb(this)};x.prototype.Y=function(){this.v=1};x.prototype.$=function(){if(this.v==1)this.v=0;nb(this)};da(x.prototype,"nq",x.prototype.enqueue);da(x.prototype,"al",x.prototype.Y);da(x.prototype,"rl",x.prototype.$);var nb=function(a){a.qa.setTimeout(m(a.pa,a),0)};
x.prototype.pa=function(){if(this.v==0&&this.Z.length){var a=this.Z.shift();this.v=2;a.win.setTimeout(m(this.na,this,a),0);nb(this)}};x.prototype.na=function(a){this.v=0;a.fn()};var ob,pb,qb,rb,sb,tb,ub,vb=function(){ub=tb=sb=rb=qb=pb=ob=j;var a=ua();if(a)if(a.indexOf("Firefox")!=-1)ob=f;else if(a.indexOf("Camino")!=-1)pb=f;else if(a.indexOf("iPhone")!=-1||a.indexOf("iPod")!=-1)qb=f;else if(a.indexOf("iPad")!=-1)rb=f;else if(a.indexOf("Android")!=-1)sb=f;else if(a.indexOf("Chrome")!=-1)tb=f;else if(a.indexOf("Safari")!=-1)ub=f};vb();var wb=Ma;var y=function(a){this.C=a;this.W=[];this.V=0;this.I=[];this.ia=0;this.O=[];this.ha=j;this.f=this.ea="";this.ga=j},xb=function(a,b,c){var d=a.C[c],e=a.W;a.C[c]=function(h){if(h&&h.length>0){var i=h.length>1?h[1].url:g;e.push([b,ja(h[0].url),i])}d(h)}},yb=function(a){a.V++},zb=function(a,b){a.I.push(b)},Ab="http://"+ga()+"/pagead/osd.js",Bb=function(a){if(!a.ha){Qa(wb);Oa(Ab);a.ha=f}},Cb=function(a,b){if(a.V>0)for(var c=a.C.document.getElementsByTagName("iframe"),d=a.ga?"google_ads_iframe_":"google_ads_frame",
e=0;e<c.length;e++){var h=c.item(e);h.src&&h.name&&h.name.indexOf(d)==0&&b(h,h.src)}},Db=function(a,b){var c=a.W;if(c.length>0)for(var d=a.C.document.getElementsByTagName("a"),e=0;e<d.length;e++)for(var h=0;h<c.length;h++)if(d.item(e).href==c[h][1]){var i=d.item(e).parentNode;if(c[h][2])for(var l=i,n=0;n<4;n++){if(l.innerHTML.indexOf(c[h][2])>0){i=l;break}l=l.parentNode}b(i,c[h][0]);c.splice(h,1);break}},Fb=function(a,b){for(var c=0;c<a.I.length;c++){var d=a.I[c],e=Eb(d);if(e)(e=a.C.document.getElementById("google_ads_div_"+
e))&&b(e,d)}};y.prototype.T=function(a){Db(this,a);Fb(this,a);Cb(this,a)};y.prototype.setupOsd=function(a,b,c){this.ia=a;this.ea=b;this.f=c};y.prototype.getOsdMode=function(){return this.ia};y.prototype.getEid=function(){return this.ea};y.prototype.getCorrelator=function(){return this.f};y.prototype.U=function(){return this.W.length+this.V+this.I.length};y.prototype.setValidOutputTypes=function(a){this.O=a};
y.prototype.registerAdBlockByType=function(a,b,c){if(this.O.length>0){for(var d=0;d<this.O.length;d++)if(this.O[d]==a){this.ga=c;if(a=="js")xb(this,b,"google_ad_request_done");else if(a=="html")yb(this);else a=="json_html"&&zb(this,b)}Bb(this)}};var Eb=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2)return a[1];return""},Gb=function(){var a=wb;a.__google_ad_urls||(a.__google_ad_urls=new y(a));return a.__google_ad_urls};o("Goog_AdSense_getAdAdapterInstance",Gb);
o("Goog_AdSense_OsdAdapter",y);o("Goog_AdSense_OsdAdapter.prototype.numBlocks",y.prototype.U);o("Goog_AdSense_OsdAdapter.prototype.findBlocks",y.prototype.T);o("Goog_AdSense_OsdAdapter.prototype.getOsdMode",y.prototype.getOsdMode);o("Goog_AdSense_OsdAdapter.prototype.getEid",y.prototype.getEid);o("Goog_AdSense_OsdAdapter.prototype.getCorrelator",y.prototype.getCorrelator);o("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",y.prototype.setValidOutputTypes);
o("Goog_AdSense_OsdAdapter.prototype.setupOsd",y.prototype.setupOsd);o("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",y.prototype.registerAdBlockByType);var Hb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ib={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",
google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Jb={google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var C=document,D=navigator,E=window;
function Kb(){var a=C.cookie,b=Math.round((new Date).getTime()/1E3),c=E.google_analytics_domain_name;c=typeof c=="undefined"?Lb("auto"):Lb(c);var d=a.indexOf("__utma="+c+".")>-1,e=a.indexOf("__utmb="+c)>-1,h=a.indexOf("__utmc="+c)>-1,i={},l=!!E&&!!E.gaGlobal;if(d){a=a.split("__utma="+c+".")[1].split(";")[0].split(".");i.sid=e&&h?a[3]+"":l&&E.gaGlobal.sid?E.gaGlobal.sid:b+"";i.vid=a[0]+"."+a[1];i.from_cookie=f}else{i.sid=l&&E.gaGlobal.sid?E.gaGlobal.sid:b+"";i.vid=l&&E.gaGlobal.vid?E.gaGlobal.vid:
(Math.round(Math.random()*2147483647)^Mb()&2147483647)+"."+b;i.from_cookie=j}i.dh=c;i.hid=l&&E.gaGlobal.hid?E.gaGlobal.hid:Math.round(Math.random()*2147483647);return E.gaGlobal=i}
function Mb(){var a=C.cookie?C.cookie:"",b=E.history.length,c,d=[D.appName,D.version,D.language?D.language:D.browserLanguage,D.platform,D.userAgent,D.javaEnabled()?1:0].join("");if(E.screen)d+=E.screen.width+"x"+E.screen.height+E.screen.colorDepth;else if(E.java){c=java.awt.Toolkit.getDefaultToolkit().getScreenSize();d+=c.screen.width+"x"+c.screen.height}d+=a;d+=C.referrer?C.referrer:"";for(a=d.length;b>0;)d+=b--^a++;return Nb(d)}
function Nb(a){var b=1,c=0,d;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){c=a.charCodeAt(d);b=(b<<6&268435455)+c+(c<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Lb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=C.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Nb(a.toLowerCase())};function Ob(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==g)this._domain_=document.domain}Ob.prototype.toString=function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"};function F(){this.w=Pb(this);this.Q=j;if(!this.w)this.Q=Qb(this)}F.prototype.P="__gads=";F.prototype.D="GoogleAdServingTest=";F.prototype.M=function(a){this.q=a._cookies_[0];if(this.q!=g){this.w=this.q._value_;Rb(this)}};da(F.prototype,"setCookieInfo",F.prototype.M);
var Sb=function(a,b){var c=(new Date).valueOf(),d=new Date;d.setTime(c+b);return d},Tb=function(a){var b=15552E6;a=Sb(a,b);b="ID=12345:T="+b;var c="/",d=document.domain;return new Ob(b,a.valueOf(),c,d)},Ub="http://"+r("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",Vb=function(a,b){if(!(a.w||!a.Q)){var c="script",d=document.domain;d=Ub+"&client="+v(b)+"&domain="+v(d);document.write("<"+c+' src="'+d+'"></'+c+">")}},Qb=function(a){document.cookie=
a.D+"Good";var b=Wb(a,a.D);if(b=b=="Good"){var c=Sb(a,-1);document.cookie=a.D+"; expires="+c.toGMTString()}return b},Pb=function(a){return a=Wb(a,a.P)},Wb=function(a,b){var c=document.cookie,d=c.indexOf(b),e="";if(d!=-1){d=d+b.length;e=c.indexOf(";",d);if(e==-1)e=c.length;e=c.substring(d,e)}return e},Rb=function(a){if(a.q!=g)if(a.w){var b=new Date;b.setTime(1E3*a.q._expires_);var c=a.q._domain_;a=a.P+a.w+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;document.cookie=a}};function Xb(a,b){try{return a.top.document==b}catch(c){}return j};var Yb=function(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]};var Zb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),$b=function(a){return a&&decodeURIComponent(a)};var ac=function(a){this.oa=(this.R=a&&a.GA_jstiming)&&this.R.load};ac.prototype.tick=function(a,b){this.oa.tick(a,b)};ac.prototype.report=function(a){var b={};b.e=a;this.R.report(this.oa,b)};var bc=function(){};p(bc,ac);bc.prototype.tick=function(){};bc.prototype.report=function(){};var cc=function(a,b,c,d){if(c<=4){b=b+"_"+c;d?a.tick(b,d+"_"+c):a.tick(b)}};var dc=function(a,b){var c=0,d=[];a&&d.push(a);if(b){var e=$a(b);e&&d.push(e)}if(d.length>0)c=Ya(d.join(":"));return c.toString()};var H=u&&Math.random()<ab&&u.GA_jstiming&&u.GA_jstiming.load&&u.location.protocol=="http:"?new ac(u):new bc(u);H.tick("js_load");function I(a){return typeof a=="function"}function ec(a,b){if(typeof a!="string"||a.length==0)return g;else if(typeof b!="string"||b.length==0)return g;return fc(J(),a,b)}o("GA_googleAddSlot",ec);function _GA_googleInitializeAdEngine(a){if(!K()){gc(hc(a));ic(K())}}o("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function jc(){J().ra=f;_GA_googleInitializeAdEngine(g);var a=K().g;a=="sync"||a=="sync_sra"?K().j():kc(J())}o("GA_googleFetchAds",jc);function lc(){_GA_googleInitializeAdEngine("iframe");Vb(window._GA_googleCookieHelper,window.GS_googleGetIdsForAdSenseService())}o("GA_googleUseIframeRendering",lc);function mc(){var a=window.GA_googleEnv.getParameter("google_ad_impl");a==g&&window.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}o("GA_googleUseSyncSRARendering",mc);
function nc(a){window.GA_googleEnv.setParameter("google_domain_reset_url",a)}o("GA_googleDomainResetUrl",nc);function oc(a){var b=Ka(Ja);pc(J(),a,b);if(K()!=g)if(K().g!="iframe"){if(qc(K()))if(K().N){b=L(J(),a);if(b==g)return;else if(!b._enabled_)return}else return;else if(M(K(),a)!=g&&!K().l)return;K().n(a)}}o("GA_googleFillSlot",oc);function rc(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;var e=Ka(Ja);pc(J(),b,e);if(K()!=g)if(K().g=="iframe"){fc(J(),a,b);a=new sc(c,d,j,f);tc(J(),b,a);K().n(b)}}
o("GA_googleFillSlotWithSize",rc);function uc(){vc(new wc(Hb));gc(g)}o("GA_googleResetAll",uc);window.google_noFetch=j;function xc(){window.google_noFetch=f}o("GA_googleNoFetch",xc);function yc(){window.google_delayFetch=f}o("GA_googleDelayFetch",yc);function sc(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}
sc.prototype.toString=function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"};function zc(a){var b={};a=a.split("?");a=a[a.length-1].split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(d[0])try{b[d[0].toLowerCase()]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(Ac," ")):unescape(d[1]):""}catch(e){}}return b}function Bc(a){a=a||document.URL;this.la=zc(a)}
Bc.prototype.getParameter=function(a){return a==g?g:this.la[a]};Bc.prototype.setParameter=function(a,b){this.la[a]=b};var Cc=function(){if(!ib)return"http://"+r("","pubads.g.doubleclick.net");return"https://"+r("","securepubads.g.doubleclick.net")};function N(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;")}function Dc(){this.G=g;this.ma=j;this.Aa=(new Date).valueOf()}
var Fc=function(a,b){if(a.G==g)if(!a.ma){a.G=window.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.G){var c=a.G.document,d=[];d.push('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');
d.push("<p>Google Ad Capture Window</p>");for(var e in b)I(b[e])||d.push(Ec(a,e,b[e]));d.push("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d.push("<script>displayTime('blocked', pageStartTime);<\/script>");d.push("<p>Total Page Load Time (ms): <label id='total'></label>");d.push("</body>\n</html>");d=d.join("\n");(e=window.GA_googleEnv.getParameter("google_capture_norender")!=g)?c.write(N(d)):c.write(d);c.close()}else a.ma=f}},Ec=function(a,b,c){a="<script>slotStartTime = (new Date()).valueOf();<\/script>";
var d="<p>Slot "+b+"</p>";c=c==g||c._html_==g?"No ad":c._html_;var e="<p>Slot Time (ms): <label id='"+b+"'></label>";b='<script>displayTime("'+b+'", slotStartTime);<\/script>';return a+d+"\n"+c+"\n"+e+b};function Gc(a){this.d={};this.F=a}var Hc=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.F)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Ic=function(a,b){for(var c in b.d)I(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};
Gc.prototype.getAttribute=function(a){return this.d[a]};Gc.prototype.h=function(){var a=[];for(var b in this.d)if(!I(this.d[b])){var c=Hb[b]||Ib[b]||Jb[b]||g,d=this.d[b];c&&d&&a.push(c+"="+v(d))}return a.join("&")};
var Kc=function(a,b,c,d){a=Jc(a,b,c,d);b=[];a[0]&&a[0].length>0&&b.push(a[0].join("&"));a[1]&&a[1].length>0&&b.push("sps="+a[1].join("|"));return b.join("&")},Jc=function(a,b,c,d){var e=[],h=[];b=b.d;for(var i in d)if(!I(i)){var l=d[i];if(l){var n="";if(b[i]!=g)n=v(b[i]);var G=[],z=-1,A=-1;for(var B in a)if(!I(a[B])){++z;if(c[B]==g)G.push("");else{var ca=c[B].d;if(ca[i]!=g){G.push(v(v(ca[i])));A=z}else G.push("")}}if(A>=0){z=v(n);n=[];n.push(z);for(z=0;z<=A;++z)n.push(G[z]);h.push(l+","+n.join(","))}else n&&
e.push(l+"="+n)}}a=[];a.push(e);a.push(h);return a};function Lc(a,b){this.L=a;this.s=b;this.aa=0;this.xa=this.S=this.X=j;this.va=this.wa=this.fa=this.sa=g}var Mc=function(a){a.S=f;a.sa=(new Date).valueOf()},Nc=function(a){a.fa=(new Date).valueOf()},Oc=function(a){a.xa=f;a.wa=(new Date).valueOf()},Pc=function(a){a.va=(new Date).valueOf()};Lc.prototype.toString=function(){return"[GA_GoogleAdSlot: pubid="+this.L+", name="+this.s+", loaded="+this.X+", tries="+this.aa+"]"};
function wc(a){this.a={};this.c=[];this.r={};this.F=a;this.ka=new Gc(this.F);this.B={};this.ra=j;this.o=g;this.ca={}}
var fc=function(a,b,c){b=new Lc(b,c);return a.a[b.s]=b},Qc=function(a,b){var c=[];for(var d in a.a)if(!I(a.a[d])){if(b){var e=L(a,d);if(e==g||!e._enabled_)continue}e=a.a[d];e.S||c.push(e)}return c},Rc=function(a,b){return Qc(a,b).length},Sc=function(a){var b=[];for(var c in a.a){var d=a.a[c];I(d)||d.S&&d.fa==g&&b.push(c)}return b},Tc=function(a){var b=0;for(var c in a.a)if(!I(a.a[c])){var d=L(a,c);d!=g&&d._enabled_&&b++}return b},Uc=function(a){for(var b in a.a)if(!I(a.a[b])){var c=a.a[b];Mc(c)}},
Vc=function(a,b){var c=a.a[b];Mc(c)},Wc=function(a,b){var c=a.a[b];Nc(c)},Xc=function(a,b){var c=a.a[b];Oc(c)},O=function(a,b){var c=a.a[b];Pc(c);cc(H,"ga_render",a.c.length,"ga_srt")},Yc=function(a){var b=0;for(var c in a.a)I(a.a[c])||b++;return b};wc.prototype.toString=function(){var a="[AdData:",b=[];for(var c in this.a)I(this.a[c])||b.push(this.a[c].toString());for(var d in this.r)I(this.r[d])||b.push("["+d+","+this.r[d]+"]");a+=b.join();a+="]";return a};
var P=function(a,b){return a.a[b]},Zc=function(a,b,c){if(!(b==g||b.length==0)){if(c==g||c.length==0)c="";var d=a.r[b];a.r[b]=d==g?c:d+","+c}};function $c(a,b){Zc(J(),a,b)}o("GA_googleAddAttr",$c);var ad=function(a,b,c){Hc(a.ka,b,c)};function bd(a,b){ad(J(),a,b)}o("GA_googleAddAdSensePageAttr",bd);var cd=function(a){return a.ka},dd=function(a,b,c,d){if(!(b==g||b.length==0)){if(K()==g||K().g!="iframe"){var e=a.a[b];if(e==g)return}e=a.B[b];if(e==g)a.B[b]=new Gc(a.F);Hc(a.B[b],c,d)}};
function ed(a,b,c){dd(J(),a,b,c)}o("GA_googleAddAdSenseSlotAttr",ed);
var fd=function(a,b){return a.B[b]},pc=function(a,b,c){a.ca[b]=c},gd=function(a,b){return a.ca[b]},hd=function(){var a=Cc();return a+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},kc=function(a){if(a.o!=g)K().j();else{var b=[];for(var c in a.a)I(a.a[c])||b.push(c);a=window.GS_googleGetIdsForAdSenseService();b=hd(window)+"&client="+escape(a)+"&page_slots="+escape(b.join());document.write("<script src = '"+b+"'><\/script>")}},id=function(a,b){a.o=b;K().N=f;K().j()};
function jd(a){id(J(),a)}o("GA_googleSetAdSlotAttributes",jd);var tc=function(a,b,c){if(a.o==g)a.o={};a.o[b]=c;K().N=f},L=function(a,b){return a.o!=g?a.o[b]:g};function kd(a,b,c){if(!c||c<0||c>1)c=0;this.ya=Math.random()<c;this.ta=a;this.ba=b+"/pagead/gen_204?id="+v(a);this.ua=[]}
var Q=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.ba+="&"+b+"="+v(c)},ld=function(a){var b=J();for(var c in b.a){var d=b.a[c];if(!I(d)&&d.L!=g){Q(a,"pub_id",d.L);break}}Q(a,"nslots",Yc(b).toString());Q(a,"pub_url",document.URL);Q(a,"pub_ref",document.referrer)},md=function(a){if(!a.ya||!a.ta||!a.ba)return j;var b=new Image;b.src=a.ba;a.ua.push(b);return f};function R(a){this.i=g;this.o={};this.p=this.b="";this.l=a;this.m=this.K=this.t=j;this.g="sync";this.za=Hb;this.u=f;this.da=this.N=j}
var ic=function(a){a.t=window.GA_googleEnv.getParameter("google_nofetch")!=g||window.google_noFetch;a.K=window.GA_googleEnv.getParameter("google_norender")!=g;a.m=window.GA_googleEnv.getParameter("google_capture")!=g||window.GA_googleEnv.getParameter("google_capture_norender")!=g;if(a.m)a.K=f;nd(a,window);a.b=a.p;var b=m(a.ja,a);od(a,window,b)},pd=function(a){a.da=f},od=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,j);return f}return j};
R.prototype.H=function(){this.m&&Fc(window.GA_googleAdCapture,this.i)};var qd=function(a){if(a.g=="sync_sra"){var b=J(),c=Yc(b);b=b.c.length;if(c!=b){a.J=new kd("sra_mismatch",Cc(),cb);Q(a.J,"correlator",a.f);Q(a.J,"fslots",b.toString());ld(a.J);md(a.J)}}},rd=function(a){H.tick("ga_onload");H.report(a.g)},sd=function(a){var b=Sc(J());if(b.length>0){a.A=new kd("missing_cb",Cc(),bb);Q(a.A,"pending",b.join());Q(a.A,"correlator",a.f);Q(a.A,"impl",a.g);ld(a.A);md(a.A)}};
R.prototype.ja=function(){rd(this);this.H();qd(this);sd(this)};var nd=function(a){var b=window.GA_googleEnv.getParameter("google_ad_url");if(b==g||b.length==0)a.p=Cc()+"/gampad/ads?";else{if(b.charAt(b.length-1)!="?")b+="?";a.p=b}};R.prototype.k=function(){};
var M=function(a,b){return a.i!=g?a.i[b]:g},td=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");return b==-1?0:parseFloat(a.substring(b+5,a.indexOf(";",b)))},Ac=/\+/g,ud=function(a,b){b=b.toLowerCase();if(b.substring(0,3)!="ca-")b="ca-"+b;return b},T=function(a,b,c){c!=g&&S(a,b,v(c.toString()))},S=function(a,b,c){if(c!=g&&c!="")a.b+=a.b.charAt(a.b.length-1)!="?"?"&"+b+"="+c:b+"="+c},vd=function(a,b){for(var c=Qc(J(),a.u),d=[],e=[],h=[],i=c.length,l=0;l<i;l++){var n=c[l];h.push(n.s);if(!(b!=
g&&b!=n.s)){d.push(n.s);e.push(ud(a,n.L))}}T(a,"client",e[0]);if(a.l)h.length>0&&T(a,"page_slots",h.join());else{T(a,"slotname",d.join());J().c.length>0&&T(a,"page_slots",J().c.join())}},wd=function(a,b,c){if(c!=g){a=b.lastIndexOf("?");a=b.indexOf("google_preview=",a);c=b.indexOf("&",a);if(c==-1){c=b.length-1;a-=1}return b.substring(0,a)+b.substring(c+1,b.length)}return b},xd=function(a,b,c){if(Xb(b,c))return c.URL;return c.referrer},zd=function(a,b,c){if(yd(a,b,c)!=c.URL)return c.domain;return""},
yd=function(a,b,c){var d=cd(J()).getAttribute("google_page_url");if(d)return d;return xd(a,b,c)},Ad=function(a,b,c,d){T(a,"url",wd(a,yd(a,window,document),window.GA_googleEnv.getParameter("google_preview")));T(a,"ref",document.referrer);T(a,"lmt",(Date.parse(document.lastModified)/1E3).toString());S(a,"dt",b.getTime());if(document.body){b=document.body.scrollHeight;var e=document.body.clientHeight;e&&b&&T(a,"cc",Math.round(e*100/b).toString())}b=f;if(b=Xa(b)){T(a,"biw",b.width);T(a,"bih",b.height)}b=
Yb(window);T(a,"ifi",b);b=Za(window);b!=0&&T(a,"ifk",b.toString());b=dc(c,gd(J(),c));T(a,"adk",b);b=window.GA_googleEnv.getParameter("deb");b!=g&&T(a,"deb",b);b=window.GA_googleEnv.getParameter("haonly");b!=g&&T(a,"haonly",b);b=cd(J());navigator.userAgent.indexOf("MSIE ")>0&&Hc(b,"google_encoding",document.charset,j);e="";if(d)e=Kc(J().a,b,J().B,a.za);else{c=fd(J(),c);if(c==g)c=b;else Ic(c,b);e=c.h()}if(e)a.b+="&"+e},Bd=function(a,b,c){var d=J().r,e=[];for(var h in d)I(d[h])||e.push(v(h)+"="+v(d[h]));
T(a,"cust_params",e.join("&"));if(b._GA_googleCookieHelper){T(a,"cookie",b._GA_googleCookieHelper.w);b._GA_googleCookieHelper.Q&&T(a,"cookie_enabled","1")}(b=zd(a,b,c))&&T(a,"cdm",b)},Cd=function(a){Kb();var b=window;S(a,"ga_vid",b.gaGlobal.vid);S(a,"ga_sid",b.gaGlobal.sid);S(a,"ga_hid",b.gaGlobal.hid);S(a,"ga_fc",b.gaGlobal.from_cookie);T(a,"ga_wpids",b.google_analytics_uacct)},Dd=function(a,b){for(var c in b){var d=b[c];I(d)||S(a,c,d)}},Fd=function(a){var b=[];if(ba(window.GS_googleGetExpIdsForAdSense)==
"function"){var c=window.GS_googleGetExpIdsForAdSense();c&&b.push(c)}(c=Ed(a.f.toString()))&&b.push(c);b.length>0&&T(a,"eid",b.join())};
R.prototype.h=function(a){this.k();Fd(this);var b=new Date;vd(this,a);Bd(this,window,document);window.GA_googleEnv.getParameter("google_preview")!=g&&S(this,"gct",window.GA_googleEnv.getParameter("google_preview"));Cd(this);Ad(this,b,a,this.l);a={};Wa(a);Dd(this,a);S(this,"flash",Ua());this.b=this.b.substring(0,2E3);this.b=this.b.replace(/%\w?$/,"");if(this.da){a=this.g=="iframe"||this.g=="fallback"?"html":"json_html";Gb().registerAdBlockByType(a,this.b,f)}return this.b};
var qc=function(a){return a.u},U=function(a,b){var c=b.getAttribute("id");return c=c.substr(18,c.length-18)},Gd=function(a,b,c,d){a='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:block;">'+d+"</ins>";return b='<ins style="position:relative;width:'+b+"px;height:"+c+'px;border:none;display:inline-table;">'+a+"</ins>"},Hd=function(a,b,c,d,e,h){var i="google_ads_iframe_"+b,l=[];b="google_ads_div_"+b;var n="border:0px;left:0;position:absolute;top:0;";l.push("<iframe id=",
i," name=",i,' width="',e,'" height="',h,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.m?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" ','style="',n,'"',' src="',N(c),'"');d!=g&&l.push(' onload="',d,'"');l.push("></iframe>");c=[];l=l.join("");c.push("<div id=",b,">");c.push(Gd(a,e,h,l));c.push("</div>");a=c.join("");document.write(a)},Id=function(a,b,c){var d=M(a,c),e=d._width_,h=d._height_;d=d._html_;var i=document.createElement("iframe");i.id="google_ads_iframe_"+
c;i.name="google_ads_iframe_"+c;i.width=e;i.height=h;i.vspace=0;i.hspace=0;i.allowTransparency="true";i.scrolling="no";i.marginWidth=0;i.marginHeight=0;i.frameBorder=0;i.style.border=0;b=document.getElementById(b);i.style.position="absolute";i.style.top=0;i.style.left=0;var l=document.createElement("ins");l.style.width=e+"px";l.style.height=h+"px";l.style.border=0;l.style.display="block";l.style.position="relative";var n=document.createElement("ins");n.style.width=e+"px";n.style.height=h+"px";n.style.border=
0;n.style.display="inline-table";n.style.position="relative";l.appendChild(i);n.appendChild(l);b.appendChild(n);if(a.m){i.contentWindow.document.write(N(d));i.scrolling="auto"}else i.contentWindow.document.write(d);i.contentWindow.document.write("<script>document.close();<\/script>");O(J(),c)};function Jd(a,b){Id(K(),a,b)}o("GA_googleCreateDomIframe",Jd);
var Kd=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=0,d=b.length;c<d;++c){var e=b[c],h=e.getAttribute("target");if(h){a.push({baseElement:e,originalTagValue:h});e.removeAttribute("target")}}return a},Ld=function(a){if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Md=function(a){var b="http://"+ga()+"/pagead/inject_object_div.js";if(parseInt(td(),10)>6)return j;if(a.indexOf(b)<0)return j;return f},Nd=function(a,
b,c){if(a.m)c=N(c);a=Kd();window.frames[b.name].contents=c;b.src=Md(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Ld(a)},Od=function(a,b,c){var d=U(a,b);try{var e=b.contentWindow?b.contentWindow.document:b.contentDocument;if(e==g)if(document.implementation&&document.implementation.createDocument)e=document.implementation.createDocument("",d,g);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return j;e.open("text/html",
"replace");a.m?e.write(N(c)):e.write(c);e.close()}catch(h){return j}return f},Pd=function(a,b){var c=U(a,b),d=P(J(),c);if(!d.X){d.X=f;d=M(a,c);var e=b.parentNode;if(d==g||d._html_==g)e.removeChild(b);else if(d._expandable_&&!(d._is_afc_&&d._is_3pas_))e.innerHTML=d._html_;else d._is_3pas_?Nd(a,b,d._html_):Od(a,b,d._html_);O(J(),c)}},Qd=function(a,b){var c="google_ads_div_"+b;c="<div id="+c+">";var d=M(a,b);if(d!=g){c+=d._html_;c+="\n</div>\n";document.write(c);O(J(),b)}},Rd=function(a,b){var c="google_ads_div_"+
b,d="<div id="+c+">";d+="\n</div>\n";document.write(d);return c},Sd=function(a){if(!a.u)return f;if(Rc(J(),a.u)>0)return f;else if(Tc(J())==0)return j},Td=function(a,b){cc(H,"ga_srt",J().c.length,"_ga_start");if(a.i==g){a.i=b;for(var c in b)I(b[c])||Wc(J(),c)}else for(c in b)if(!I(b[c])){a.i[c]=b[c];Wc(J(),c)}var d=j;for(c in b)if(!I(b[c])){var e=b[c];if(d){e._cookies_=[Tb(window._GA_googleCookieHelper)];d=j}e!=g&&e._cookies_!=g&&window._GA_googleCookieHelper.M(e)}};function Ud(a){Td(K(),a)}
o("GA_googleSetAdContentsBySlot",Ud);function V(a){R.call(this,a);this.u=j;this.f=(new Date).getTime();this.g=a?"sync_sra":"sync"}p(V,R);V.prototype.k=function(){this.b=this.p;T(this,"correlator",this.f.toString());S(this,"output","json_html");S(this,"callback","GA_googleSetAdContentsBySlotForSync");this.l?S(this,"impl","ss"):S(this,"impl","s");Vd(this,J().c);this.l||Wd(this,J().c,this.i)};
var Vd=function(a,b){for(var c=0,d=f,e=0;e<b.length;++e){var h=a.i&&a.i[b[e]];if(h)if(h._is_afc_==undefined){d=j;break}else c=2*c+(h._is_afc_?1:0)}d&&S(a,"prev_afc",c)},Wd=function(a,b,c){if(b&&c){for(var d=[],e=[],h=b.length-1,i=0;i<h;i++){var l=b[i];if((l=c[l])&&l._cids_&&l._a2ids_){d.push(l._cids_[0]);e.push(l._a2ids_[0])}else{d.push("");e.push("")}}if(d.length>0){b=d.join(",");e=e.join(",");T(a,"a2ids",e);T(a,"cids",b)}}},Xd=function(a,b){var c=J().a;c=c[b];if(c!=g)if(!a.t){a.h(c.s);Vc(J(),b);
document.write("<script src = '"+a.b+"'><\/script>")}},Zd=function(a,b){Td(a,b);if(a.l)if(J().c.length==1){var c=J().c[0];Yd(a,c);return}for(c in b)I(b[c])||Yd(a,c)};function $d(a){Zd(K(),a)}o("GA_googleSetAdContentsBySlotForSync",$d);V.prototype.j=function(){Sd(this)};var ae=function(a){a.h(g);document.write("<script src = '"+a.b+"'><\/script>");Uc(J())};V.prototype.n=function(a){J().c.push(a);cc(H,"_ga_start",J().c.length);if(this.l)J().c.length==1?ae(this):Yd(this,a);else Xd(this,a)};
var be=function(a,b,c){if(b.google_js_backfill){a="script";c.write("<"+a+' src="'+Na+'"></'+a+">")}},Yd=function(a,b){ce(a,window,document,b)},ce=function(a,b,c,d){var e=P(J(),d);if(e!=g){e=M(a,d);Xc(J(),d);if(e==g||e._empty_){be(a,b,c,d);O(J(),d)}else if(a.K&&!a.m)O(J(),d);else if(e._snippet_&&!e._is_afc_&&!a.m)Qd(a,d);else if(b.navigator.userAgent.indexOf("MSIE ")>0){c="GA_googleSyncAdSlotLoaded(this);";var h="about:blank";if(b=b.GA_googleEnv.getParameter("google_domain_reset_url")){var i=$b(b.match(Zb)[3]||
g);if(i===g||i.indexOf(document.domain)>=0)h=b}Hd(a,d,h,c,e._width_,e._height_)}else{a=Rd(a,d);c.write("<script>GA_googleCreateDomIframe('"+a+"' ,'"+d+"');<\/script>")}}},de=function(a,b){var c=U(a,b);P(J(),c);Pd(a,b)};function ee(a){de(K(),a)}o("GA_googleSyncAdSlotLoaded",ee);function W(a){R.call(this,a);this.f=(new Date).getTime();this.g="async"}p(W,R);
W.prototype.k=function(){this.b=this.p;fe(this);T(this,"correlator",this.f.toString());S(this,"output","json_html");S(this,"callback","GA_googleSetAdContentsBySlot");S(this,"impl","a")};var fe=function(a){a.delay=500;var b=window.GA_googleEnv.getParameter("google_async_delay");if(b!=g)a.delay=1E3*b};W.prototype.j=function(){if(Sd(this))this.t||window.setTimeout("GA_googleReallyFetchAds();",20)};
var ge=function(a){if(Rc(J(),a.u)!=0){var b=document.getElementsByTagName("head")[0];if(a.l){var c=document.createElement("script");c.src=a.h(g);b.appendChild(c);Uc(J())}else{var d=J().a;for(var e in d)if(!I(d[e])){c=document.createElement("script");c.src=a.h(e);b.appendChild(c);Vc(J(),e)}}}};function he(){ge(K())}o("GA_googleReallyFetchAds",he);
W.prototype.n=function(a){var b=P(J(),a);if(b!=g){J().c.push(a);b="GA_googleAsyncAdSlotLoaded(this);";var c=L(J(),a);Hd(this,a,"about:blank",b,c._width_,c._height_)}};var je=function(a,b){var c=U(a,b);P(J(),c);!a.t&&!a.K&&ie(a,b)};function ke(a){je(K(),a)}o("GA_googleAsyncAdSlotLoaded",ke);var ie=function(a,b){var c=U(a,b),d=P(J(),c);if(a.i==g||a.i[c]==g){if(!(d.aa>30)){window.setTimeout(function(){ie(K(),b)},a.delay);d.aa++}}else Pd(a,b)};W.prototype.H=function(){};
function X(a){R.call(this,a);this.f=(new Date).getTime();this.g="fallback"}p(X,R);X.prototype.k=function(){this.b=this.p;T(this,"correlator",this.f.toString());S(this,"output","html");S(this,"impl","fb")};X.prototype.j=function(){Sd(this)};X.prototype.z=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+v(a)}else a=this.h(a);return a};X.prototype.n=function(a){var b=L(J(),a);if(b!=g){J().c.push(a);if(!this.t){var c=this.z(a);Hd(this,a,c,g,b._width_,b._height_)}}};
function Y(a){R.call(this,a);this.f=(new Date).getTime();this.N=f;this.g="iframe"}p(Y,R);Y.prototype.k=function(){this.b=this.p;T(this,"correlator",this.f.toString());S(this,"output","html");S(this,"impl","ifr")};Y.prototype.j=function(){Sd(this)};Y.prototype.z=function(a){if(this.l){this.h(g);a=this.b+"&currentslot="+v(a)}else a=this.h(a);return a};Y.prototype.n=function(a){var b=L(J(),a);if(b!=g){J().c.push(a);if(!this.t){var c=this.z(a);Hd(this,a,c,g,b._width_,b._height_)}}};
var le=function(){if(Ta()){var a=td();return a<=5}else if(w("firefox")){var b=navigator.userAgent.indexOf("Firefox")+8;a=parseInt(navigator.userAgent.charAt(b),10);b=navigator.userAgent.slice(b);return a<1}else if(w("safari")){b=navigator.userAgent.indexOf("Safari")+7;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<412}else if(window.opera!=g){b=navigator.userAgent.indexOf("Opera")+6;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<9}else if(!Ta()&&!w("safari")&&w("mozilla")){b=navigator.userAgent.indexOf("Netscape")+
9;b=navigator.userAgent.slice(b);a=parseInt(b,10);return a<7}else return f},me=function(){if(Ta()){var a=td();return a>5}else if(w("firefox")){a=navigator.userAgent.indexOf("Firefox")+8;var b=parseInt(navigator.userAgent.charAt(a),10);navigator.userAgent.slice(a);return b>1}return j},ne=function(){if(le())return"fallback";else if(window.google_delayFetch&&me())return"async";return"sync"},hc=function(a){var b=g;if(typeof a!="undefined"&&a!=g)b=a;else{b=window.GA_googleEnv.getParameter("google_ad_impl");
if(b==g)b=ne()}switch(b){case "async":return new W(j);case "sync":return new V(j);case "sync_sra":return new V(f);case "fallback":return new X(j);case "iframe":return new Y(j);default:return new X(j)}},Z;function J(){Z||(Z=new wc(Hb));return Z}function vc(a){delete Z;Z=a}var $;function K(){$||($=g);return $}function gc(a){delete $;$=a}if(typeof window.GA_googleEnv=="undefined")window.GA_googleEnv=new Bc;if(typeof window.GA_googleAdCapture=="undefined")window.GA_googleAdCapture=new Dc;
if(window._GA_googleCookieHelper==g)window._GA_googleCookieHelper=new F(g);function Ed(a){var b=Gb(),c=b.getEid();if(c==""){if(c=oe(window)){var d=b.getOsdMode();if(c=="36815006"||c=="36813008"){b.setValidOutputTypes(["html","json_html"]);d=c=="36815006"?1:0}b.setupOsd(d,c,a);(a=K())&&pd(a)}}else if(c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007")c="";return c}
function oe(a){if((a.google_unique_id||0)!=0)return"";a=Va(["36815005","36815006"],db);if(a=="")a=Va(["36813007","36813008"],eb);return a}H.tick("js_parse","js_load");H.tick("jl");})()
